name: Publish Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  win-build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run dist-win
    - name: Unpack zip
      run: |
        md dist\win
        tar -xf dist\OpenExonautClient-Windows-Portable-0.9.1.zip -C dist\win
    - name: Install NSIS
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install nsis
    - name: Create NSIS installer
      run: |
        cp build\icon.ico dist\win\OpenExonautClient\
        makensis installer.nsi
    - name: Remove intermediate files
      run: rd -r dist\win
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-win
        path: dist
  mac-build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run pack-mac
    - name: Unpack zip
      run: |
        mkdir -p dist/mac
        tar -xf dist/OpenExonautClient-MacOS-Portable-0.9.1.zip -C dist/mac
    - name: Copy branding files
      run: |
        cp build/icon.icns dist/mac/OpenExonautClient.app/Contents/Resources/
        cp build/Info.plist dist/mac/OpenExonautClient.app/Contents/
        rm -rf dist/mac/OpenExonautClient.app/Contents/Resources/en.lproj
    - name: Install create-dmg
      run: brew install create-dmg
    - name: Create .dmg file
      run: |
        create-dmg --volname OpenExonaut \
        --window-pos 200 120 --window-size 660 400 \
        --icon-size 100 --icon OpenExonautClient.app 160 100 \
        --app-drop-link 500 100 \
        --add-file "MacOS Instructions.rtf" "build/MacOS Instructions.rtf" 330 260 \
        --background build/dmg_bg.tiff dist/OpenExonautClient-MacOS-Installer-0.9.1.dmg dist/mac
    - name: Remove intermediate files
      run: rm -rf dist/mac dist/OpenExonautClient-MacOS-Portable-0.9.1.zip
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-mac
        path: dist
