name: Publish Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  win-build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run dist-win
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-win
        path: dist
  mac-build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Pack into zip and create installer
      run: npm run pack-mac
    - name: Unpack zip
      run: mkdir -p dist/mac && tar -xf dist/OpenExonautClient-MacOS-Portable-0.9.0.zip -C dist/mac
    - name: Install create-dmg
      run: brew install create-dmg
    - name: Create .dmg file
      run: |
        create-dmg --volname OpenExonaut \
        --window-pos 200 120 --window-size 660 400 \
        --icon-size 100 --icon OpenExonautClient.app 160 100 \
        --app-drop-link 500 100 \
        --add-file "MacOS Instructions.rtf" "build/MacOS Instructions.rtf" 330 260 \
        --background build/dmg_bg.png dist/OpenExonautClient-MacOS-Installer-0.9.0.dmg dist/mac
    - name: Remove intermediate files
      run: rm -rf dist/mac
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifact-mac
        path: dist
